basePath: /api/v1
definitions:
  main.User:
    properties:
      firstName:
        type: string
      id:
        type: string
      secondName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample REST API to demonstrate in generating the Swagger
    documentation.
  title: APISwagger
  version: "1.0"
paths:
  /users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: Internal
      summary: Get a list of users
  /users/{id}:
    get:
      description: Get details of a specific user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: Get user by ID
swagger: "2.0"
