package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func cloneRepo(repoURL, targetDir string) error {
	repoName := strings.TrimSuffix(filepath.Base(repoURL), ".git")
	repoPath := filepath.Join(targetDir, repoName)

	if _, err := os.Stat(repoPath); err == nil {
		fmt.Printf("Repo '%s' already exists. Skipping.\n", repoName)
		return nil
	}

	fmt.Printf("Cloning '%s' into '%s'...\n", repoURL, repoPath)
	cmd := exec.Command("git", "clone", repoURL, repoPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func main() {
	targetDir := "c://Users//dinesh.natukula//Documents//backend-services-new-repo//" // Change as needed
	repos := []string{
		// "https://gitlab.pragmaticplaysports.com/ppbet/backendservices/aggregationworker.git",
		// "https://gitlab.pragmaticplaysports.com/ppbet/backendservices/archivecleanup.git",
		// "https://gitlab.pragmaticplaysports.com/ppbet/backendservices/archiving.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bbprocessor.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/authtri.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betbasketd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betbuilder.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betbasketdbd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betcounter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betplacement.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betsettlementd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/betsettler.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bettransactionsd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bettransferd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/e3fcontentadapterbg.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bonusawarder.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bonusbuilder.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/bonusredemption.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/e3fbrandmapper.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/e3fcontentadapter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/fsmonitorracing.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/fsmonitord.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/foreximported.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/fieldbookworker.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/fieldbookrestapis.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/feedinventory.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/fsmonitorbg.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/favourite.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/ermabetupdatesd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/dictionaryd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/dgoj-report-generator.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/databetreceiver.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/databetmts.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/databetcontentadapter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/e3fcarestd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/competitionfix.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/competitioncategoryd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/coagentd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/clientlogger.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/cashoutcalcd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/promobuilder.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/priceaggregator.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/prabetcacher.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/pra.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/playerstats.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/playerriskmanager.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/playerpreference.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/pamgateway.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/optimovepublisher.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/offervald.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/odsd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/nontxnpamgw.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/mtsintegration.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/migrations.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/masterofferracing.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/masteroffer.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/livedocd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/live-odds.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/kafkasync.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/idemia-vault-proxy.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/streamingdataprocessor.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/streaming-event-mapper.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/streaming.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/streambatchprocess.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/sslnreceiver.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/sslncontentadapter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/signposting.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/segmentmanager.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/searchqueryprocessor.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/searchdatastore.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/e3scoringd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/scheduler.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/rskcontentadapter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/retryrecon-betplacement.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/rasfeedadapter.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/rasbrandmapper.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/quickhealutility.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/ptlworker.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/promoscheduler.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/promoruleengine.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/wallettransactiond.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/walletd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/user.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/uibackendpromotion.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/uibackend-betrisks.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/topbetstatsd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/topbetsrestd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/topbetd.git",
		"https://gitlab.pragmaticplaysports.com/ppbet/backendservices/tokenmanager.git",

		// Old ONes.....................
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/uibackendbetrisks.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/player-risk-manager.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/player-preference.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/playerstats.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/nontxnpamgw.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/kafka-sync.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/aggregationworker.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/backend-sportsbook-docker.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/mts-integration.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/retryrecon-betplacement.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/migrations.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/wallettransactiond.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/walletd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/user.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/ptlworker.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/prabetcacher.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/pra.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/playerstats.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/livedocd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/liveaggregationsd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/foreximporterd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/ermabetupdatesd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/fieldbookworker.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/fieldbookrestapis.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/configauditd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/bettransferd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/bettransactionsd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betsettler.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betsettlementd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betplacer.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betbasketdbd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betbasketd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/authtri.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/configrestd.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/partner_onboarding.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/uibackend.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/priceaggregator.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/bonusredemption.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/bonusawarder.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/bbprocessor.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/betbuilder.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/favourite.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/feedinventorystore.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/sslnreceiver.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/sslncontentadapter.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/e3dlite.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/signposting.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/rskcontentadapter.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/feed-inventory.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/uibackend-promotion.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/fsmonitorracing.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/optimove-publisher.git",",
		// // ""https://gitlab.gametechlabs.net/ppbet/backend-services/odds-cacher.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/fsmonitorbg.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/mock-service.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/brcontentadapter.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/bgcontentadapter.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/scoring.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/debezium-connect.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/feedsearch.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/feedmapper.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/racingbetmanagement.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/migrations.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/ppbet_library.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/promobuilder.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/promoruleengine.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/dgoj-report-generator.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/idemia-vault-proxy.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/live-odds.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/promoscheduler.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/beteventloadgenerator.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/marginmonitord.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/odsd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/rmachangelog.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/topbetd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/topbetsrestd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/topbetstatsd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/translationsd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/translcachebrd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/wallettransactiongeneratord.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/masteroffer.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/brandmapper.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/contentadapterrest.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/marginadjustmentd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/liveofferd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/livedocd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/liveclient.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/liveaggregationsd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/latencylogstats.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/liveemad.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/latencytester.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/latencylogstats.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/fsmonitord.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/flowmonitor.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/fieldbookrestapis.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/configauditd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/dictionaryd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/competitioncategoryd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/cashoutcalcd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/cashouttool.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/coagentd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/archivecleanup.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/brandmappermond.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/sampleawsecr.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/alerts-history.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/configrestd.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/alertsworker.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/archiving.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/authtri.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/autocashouthandler.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/autocashoutrulearchived.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/bgsmonitord.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/brandedmetad.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/brandmappermond.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/partner_onboarding.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/betscounter.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/rasfeedadapter.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/rasbrandmapper.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/masterofferracing.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/streaming.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/terraform.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/bonusbuilder.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/betrestrictions.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/streaming-data-processor.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/stream-batch-process.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/event-mapper.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/uibackend.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/quickhealutility.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/betbuilder.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/favourite.git",",
		// ""https://gitlab.gametechlabs.net/ppbet/backend-services/competitionfix.git",",
	}

	if err := os.MkdirAll(targetDir, 0755); err != nil {
		fmt.Println("Error creating target directory:", err)
		os.Exit(1)
	}

	for _, repo := range repos {
		if err := cloneRepo(repo, targetDir); err != nil {
			fmt.Printf("Failed to clone %s: %v\n", repo, err)
		}
	}
}
